### PR TITLE
2038/add vulcan checks

### LINKED ISSUE #2038: Installing GUM Tool on Fedora 43
I've tried installing Gum Tool on Fedora 43 with the install script, the manual process, and via Bottles. 

All of them result in some flavor of the following error when I launch gum:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.Release(IntPtr)
   at SharpDX.ComObject.SharpDX.IUnknown.Release()
   at SharpDX.ComObject.Dispose(Boolean)
   at SharpDX.DisposeBase.CheckAndDispose(Boolean)
   at SharpDX.DisposeBase.Dispose()
```

Is this something anyone has encountered before?

Here is the full output of when I launch GUM with wine: [gum_output.txt](https://github.com/user-attachments/files/24848618/gum_output.txt)

### PR DESCRIPTION
**Pull request by kaltinril**
fixes #2038 

this will install vulcan support if it's detected as available
it will also default to that

the use can revert by running: `gum d3d`
or migrate back by running: `gum dvxk`
they can still upgrade by running: `gum upgrade`

I also passed the quiet flag, so the dotnet 8 now installed without popups

Docs need to be updated still though

### CODE REVIEW

**Comment by kaltinril** [comment]
screenshots from running the commands

Screenshot from 2026-02-16 16-01-43

Screenshot from 2026-02-16 15-58-30

screenshot in gum on linux

Screenshot from 2026-02-16 16-02-00

screenshot installing gum  (with prompt, prompt is no longer in script)
Screenshot from 2026-02-16 15-36-32

**Comment by kaltinril** [comment]
converted to draft

**Comment by kaltinril** [comment]
Ok, I tested this pretty good on my ubuntu 24.04.  Apparently I had messed up drivers and after removing an old kernal folder, i finally got the nvidia drivers correctly installed.



then i tested d3d first and it worked

then I switched to dxvk and it didn't, but that was because my os was messed up still and I had to install 

so i had to
purge 6.17 kernal that was old
reinstall nvidia-driver-535
install libvulkan1:i386

after that, it worked.



I'm going to make it install dxvk but default to d3d and users can manually switch to dxvk via



gum dxvk

then run gum with

gum

**Comment by kaltinril** [comment]
Going to make a few more small changes first

File: setup_gum_linux.sh [hunk 1]
```diff
@@ -284,11 +257,37 @@ rm -f "$GUM_ZIP_FILE" \
...
+echo "Reverting to WineD3D as the default renderer..."
+run_and_write_log WINEPREFIX="$GUM_WINE_PREFIX_PATH" winetricks d3d8=builtin d3d9=builtin d3d10=builtin d3d10_1=builtin d3d10core=builtin d3d11=builtin dxgi=builtin
+echo " - DXVK installed. WineD3D is the default. To switch: ~/bin/gum dxvk"
+
 ################################################################################
 ### Define the script variables
 ################################################################################
 echo "Creating gum script and adding to path"
-GUM_EXE_PATH=$(find "$GUM_WINE_EXTRACT_DIR" -name "Gum.exe" -type f)
+GUM_EXE_PATH=$(find "$GUM_WINE_EXTRACT_DIR" -name "Gum.exe" -type f | head -n1)
```
Comment (kaltinril) [inline setup_gum_linux.sh]: In the, VERY unlikely event there are 2 in the folder

**Comment by kaltinril** [comment]
OK, this is ready, MAC still doesn't work on my non apple silicon device and I don't have an apple silicon to test. 

However I split the mac code out so that we don't have to keep trying to pay attention to it, since it's already not working.
